// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03Q9xKg4SebADu4AJUsmGBVRybitOVBU',
    appId: '1:509384511547:web:551134bf0863de739dcc1e',
    messagingSenderId: '509384511547',
    projectId: 'upmarket-236d0',
    authDomain: 'upmarket-236d0.firebaseapp.com',
    storageBucket: 'upmarket-236d0.appspot.com',
    measurementId: 'G-DD8GGFF1YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWroGg3mdgIdMab-n-xSNqmIoglVR5J_Q',
    appId: '1:509384511547:android:9eea6ef035bbaa139dcc1e',
    messagingSenderId: '509384511547',
    projectId: 'upmarket-236d0',
    storageBucket: 'upmarket-236d0.appspot.com',
  );
}
